version: '3.8'

services:
  # NestJS API service with SSL
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=host.docker.internal  # Special DNS name to reach the host machine
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_DATABASE}  # Customize this to your database name
      # SSL Environment Variables
      - SSL_KEY_PATH=/app/certs/server.key
      - SSL_CERT_PATH=/app/certs/server.crt
    ports:
      - "3000:3000"  # HTTP port
      - "3443:3443"  # HTTPS port
    volumes:
      - ./src:/app/src  # For hot-reload during development
      - ./certs:/app/certs  # Mount SSL certificates from host
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Required for Docker Linux
